tools_manager/urls.py
from django.conf.urls import include, url

from tools_manager.c_views import *
from common import views
from common.common_views import *

urlpatterns = [
    # 工具类型
    url(r'^tools_types_list/', include([
        url(r'(?P<pk>\d+)/tools_types_edit_action/', simple_edit_action),
        url(r'(?P<pk>\d+)/tools_types_edit/', simple_edit),
        url(r'tools_types_add_action/', simple_add_action),
        url(r'tools_types_add/', simple_add),
        url(r'(?P<pk>\d+)/delete_entity/', simple_delete_entity),
        url(r'batch_delete_entity/', simple_batch_delete_entity),
        url(r'$', simple_list),
    ]), {
            'args': {
                'modulename': 'tools_manager.models',
                'modelname': 'ToolsTypes',
                'list_url': '/frontend/tools_manager/tools_types_list/',
                'form_template_path': 'frontend/common/basic_form.html',
                'template_path': 'frontend/tools_manager/tools_types_list.html',
                'add_title': '新增工具类型',
                'add_action': '/frontend/tools_manager/tools_types_list/tools_types_add_action/',
                'edit_title': '编辑工具类型',
                'edit_action': '/frontend/tools_manager/tools_types_list/%s/tools_types_edit_action/',
            }
        }),
    url(r'^tools_script_list/tool_execute_action/', tool_execute_action),
    url(r'^tools_script_list/(?P<pk>\d+)/tool_execute/', tool_execute),
    url(r'^tools_script_list/(?P<pk>\d+)/tool_execute_history/', tool_execute_history),
    url(r'^tools_script_list/', include([
        url(r'(?P<pk>\d+)/tools_script_edit_action/', simple_edit_action),
        url(r'(?P<pk>\d+)/tools_script_edit/', simple_edit),
        url(r'tools_script_add_action/', simple_add_action),
        url(r'tools_script_add/', simple_add),
        url(r'batch_delete_entity/', simple_batch_delete_entity),
        url(r'(?P<pk>\d+)/delete_entity/', simple_delete_entity),
        url(r'$', simple_list),
    ]), {
            'args': {
                'modulename': 'tools_manager.models',
                'modelname': 'ToolsScript',
                'list_url': '/frontend/tools_manager/tools_script_list/',
                'template_path': 'frontend/tools_manager/tools_script_list.html',
                'plugin_name': 'tool_script_list_plugin',
                'form_template_path': 'frontend/tools_manager/tools_script_form.html',
                'add_title': '新增工具',
                'add_action': '/frontend/tools_manager/tools_script_list/tools_script_add_action/',
                'edit_title': '编辑工具',
                'edit_action': '/frontend/tools_manager/tools_script_list/%s/tools_script_edit_action/',
            }
        }),

]

urls.py
# -*- coding: utf-8 -*-
"""saltops URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework import routers

# from deploy_manager.serializer import UserViewSet
from common import views
from deploy_manager.views import *
from saltops import settings

router = routers.DefaultRouter()
router.register(r'projectversionViewSet', ProjectVersionViewSet)
router.register(r'projectViewSet', ProjectViewSet)
router.register(r'deployJobViewSet', DeployJobViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url('^searchableselect/', include('searchableselect.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
    url(r'^mainform/$', views.mainform, name='mainform'),
    url(r'^dashboard/$', views.dashboard, name='mainform'),
    url(r'^frontend/cmdb/', include('cmdb.urls')),
    url(r'^frontend/tools_manager/', include('tools_manager.urls')),
    url(r'^frontend/deploy_manager/', include('deploy_manager.urls'))
]

# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ]
admin.site.site_header = 'SaltOps'
admin.site.site_title = 'SaltOps'

tools_manager/models/ToolsExecDetailHistory.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from tools_manager.models.ToolsExecJob import ToolsExecJob


class ToolsExecDetailHistory(BaseModel):
    tool_exec_history = models.ForeignKey(ToolsExecJob, blank=True, null=True)
    host = models.ForeignKey(Host, verbose_name='目标主机', blank=True, null=True)
    exec_result = models.TextField(verbose_name='执行结果', blank=True, null=True, default="")
    err_msg = models.TextField(verbose_name='错误信息', blank=True, null=True, default="")

    def __str__(self):
        return self.host.host_name

    class Meta:
        verbose_name = "工具详细信息"
        verbose_name_plural = verbose_name

tools_manager/models/ToolsExecJob.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from tools_manager.models.ToolsScript import ToolsScript


class ToolsExecJob(BaseModel):
    tools = models.ForeignKey(ToolsScript, verbose_name='工具')
    hosts = models.ManyToManyField(Host, verbose_name='目标主机')
    param = models.TextField(verbose_name='执行参数', blank=True, null=True, default="")

    def __str__(self):
        return self.param

    class Meta:
        verbose_name = "执行记录"
        verbose_name_plural = verbose_name

tools_manager/models/ToolsScript.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel
from tools_manager.models.ToolsTypes import ToolsTypes

TOOL_RUN_TYPE = (
    (0, 'SaltState'),
    (1, 'Shell'),
    (2, 'PowerShell'),
    (3, 'Python'),
    (4, 'Salt命令'),
    (5, 'Windows批处理')
)


class ToolsScript(BaseModel):
    name = models.CharField(max_length=255, verbose_name='工具名称')
    tool_script = models.TextField(verbose_name='脚本')
    tools_type = models.ForeignKey(ToolsTypes, verbose_name='工具类型')
    tool_run_type = models.IntegerField(verbose_name='脚本类型', choices=(TOOL_RUN_TYPE), default=0)
    comment = models.TextField(verbose_name='工具说明', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "工具"
        verbose_name_plural = verbose_name

tools_manager/models/ToolsTypes.py
from django.db import models

from cmdb.models import Host
from common.models import BaseModel


class ToolsTypes(BaseModel):
    name = models.CharField(max_length=255, verbose_name='类型名称')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "工具类型"
        verbose_name_plural = verbose_name

tools_manager/views.py
from django.shortcuts import render

# Create your views here.

templates/frontend/tools_manager/tool_script_execute_form.html
{% extends 'frontend/common/basic_layout.html' %}

{% block content %}

    <link href="/static/hplus/css/plugins/chosen/chosen.css" rel="stylesheet">
    <script src="/static/hplus/js/plugins/chosen/chosen.jquery.js"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>执行工具
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" action="{{ action }}" onsubmit="return preSubmit()" class="form-horizontal">

                            {% csrf_token %}
                            <input type="hidden" id="id" name="id" value="{{ pk }}"/>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> 主机组</label>
                                <div class="col-sm-10">
                                    <select data-placeholder="选择主机组"
                                            multiple class="form-control chosen-select" id="hostgroup"
                                            tabindex="4">
                                        {% for o in hostgroup %}
                                            <option value="{{ o.id }}">{{ o.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> 主机</label>
                                <div class="col-sm-10">
                                    <select data-placeholder="选择主机"
                                            multiple class="form-control chosen-select"
                                            id="hosts"
                                            tabindex="4">
                                        {% for o in hosts %}
                                            <option value="{{ o.id }}">{{ o.host_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> 执行命令</label>
                                <div class="col-sm-10">
                                    <div class="col-sm-10" style="height: 300px" name="tool_script_editor"
                                         id="id_tool_script_editor" class="form-control"></div>
                                    <textarea id="id_tool_script" name="tool_script"
                                              style="display: none">{{ entity.tool_script|default_if_none:"" }}</textarea>
                                </div>
                            </div>
                            <hr/>
                            {% for k,v in param_list %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label"> {{ k }}</label>
                                    <div class="col-sm-10">
                                        <input id="{{ v }}" name="{{ v }}" placeholder="{{ v }}" class="form-control"/>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="hr-line-dashed" id="result_line"></div>
                            <div id="result">

                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a href="javascript:void(0)" class="btn btn-primary"
                                       onclick="execute()">执行</a>
                                    <a class="btn btn-white" href="javascript:history.go(-1)">取消</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/asserts/require.js"></script>
    <script>
        function execute() {
            layer.load();
            var hosts_id = $('#hosts').val();
            hosts_str = "";
            if (hosts_id != null) {
                for (var i = 0; i < hosts_id.length; i++) {
                    hosts_str += hosts_id[i] + ',';
                }
                hosts_str = hosts_str.substr(0, hosts_str.length - 1)
            }

            var hostsgroup_id = $('#hostgroup').val();
            hostsgroup_str = "";
            if (hostsgroup_id != null) {
                for (var i = 0; i < hostsgroup_id.length; i++) {
                    hostsgroup_str += hostsgroup_id[i] + ',';
                }
                hostsgroup_str = hostsgroup_str.substr(0, hostsgroup_str.length - 1)
            }
            $.post('/frontend/tools_manager/tools_script_list/tool_execute_action/', {
                'hostids': hosts_str,
                'hostgroup_ids': hostsgroup_str,
                'id': '{{ pk }}',
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                {% for k,v in param_list %}
                    '{{ v }}': $('#{{ v }}').val()
                {% endfor %}
            }, function (rs) {
                $('#result').empty()
                debugger;
                var obj = JSON.parse(rs)
                var content = "<h3>执行结果</h3>"
                for (var i = 0; i < obj.length; i++) {
                    content += '<div class="form-group">' +
                        ' <label class="col-sm-2 control-label"> ' + obj[i].host + '</label>' +
                        '<div class="col-sm-10">' +
                        '<div class="col-sm-10" class="form-control"></div>' +
                        obj[i].exec_result.replace(/\n/g, "<br/>") +
                        '<br/><p>其他信息:</p>' +
                        obj[i].err_msg.replace(/\n/g, "<br/>") +
                        '</div> </div>'
                }
                $('#result').append(content)
                layer.closeAll('loading');
            })
        }
        var editor;
        $(document).ready(function () {
            $('.chosen-select').chosen();
            require.config({paths: {ace: "/static/asserts/ace/lib/ace"}})
            define('editor', ['ace/ace'],
                function (ace, langtools) {
                    editor = ace.edit("id_tool_script_editor");
                    editor.setTheme("ace/theme/xcode");
                    editor.session.setMode("ace/mode/yaml");
                    editor.setReadOnly(true);
                    require(["ace/requirejs/text!src/ace"], function (e) {
                        editor.setValue($('#id_tool_script').val());
                    })
                }
            );
            require(['editor'])
        });
    </script>
{% endblock %}

templates/frontend/tools_manager/tool_script_execute_history.html
{% extends 'frontend/common/basic_layout.html' %}

{% block content %}
    <div class="col-sm-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>执行记录</h5>
                <a class=" pull-right" href="javascript:history.go(-1)">返回</a>
            </div>

            <div class="ibox-content timeline">
                {% for o in result_list %}
                    <div class="timeline-item">
                        <div class="row">
                            <div class="col-xs-4 date">
                                <i class="fa fa-briefcase"></i> {{ o.create_time }}
                                <br>
                                <small class="text-navy">{{ o.human_time }}</small>
                            </div>
                            <div class="col-xs-7 content no-top-border">
                                <p class="m-b-xs"><strong>主机数量:{{ o.hosts_count }}</strong>
                                    执行成功:{{ o.success_count }}
                                    执行失败:{{ o.err_count }}
                                </p>
                                <p>{{ o.hosts }}</p>
                                <a href="javascript:void(0)" onclick="showHistory('{{ o.id }}')">详细信息</a>
                                <div id="{{ o.id }}" style="display: none">
                                    {% for v in o.result_hist %}
                                        <p>{{ v.host }}</p>
                                        <hr/>
                                        <p>
                                            {{ v.exec_result|replace_to_br }}
                                        </p>
                                        <hr/>
                                        <p>
                                            {{ v.err_msg|replace_to_br }}
                                        </p>
                                    {% endfor %}

                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="hr-line-dashed"></div>
            {% include 'frontend/common/pagination.html' %}
        </div>
    </div>
    <script>
        function showHistory(id) {
            $('#' + id).show()
        }
    </script>
{% endblock %}

templates/frontend/tools_manager/tools_script_form.html
{% extends 'frontend/common/basic_layout.html' %}

{% block content %}
    <script src="/static/asserts/require.js"></script>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>{{ title }}
                        </h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" action="{{ action }}" onsubmit="return preSubmit()" class="form-horizontal">
                            {% csrf_token %}
                            <input type="hidden" id="id" name="id" value="{{ pk }}"/>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.name.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tool_script.label_tag }}</label>
                                <div class="col-sm-10" style="height: 200px" name="tool_script_editor"
                                     id="id_tool_script_editor"></div>
                                <textarea id="id_tool_script" name="tool_script"
                                          style="display: none">{{ form.tool_script.value|default_if_none:"" }}</textarea>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tools_type.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.tools_type }}
                                    {{ form.tools_type.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.tool_run_type.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.tool_run_type }}
                                    {{ form.tool_run_type.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"> {{ form.comment.label_tag }}</label>
                                <div class="col-sm-10">
                                    {{ form.comment }}
                                    {{ form.comment.errors }}
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-primary" type="submit">保存</button>
                                    <a class="btn btn-white" href="javascript:history.go(-1)">取消</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var editor;
        function preSubmit() {
            $('#id_tool_script').val(editor.getValue())
            return true;
        }
        $(document).ready(function () {
            var fieldObj = $('.form-horizontal input')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
            fieldObj = $('.form-horizontal textarea')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }

            fieldObj = $('.form-horizontal select')
            for (var i = 0; i < fieldObj.length; i++) {
                $(fieldObj[i]).addClass('form-control')
            }
        })

        require.config({paths: {ace: "/static/asserts/ace/lib/ace"}})


        define('editor', ['ace/ace'],
            function (ace, langtools) {
                {#                console.log("This is the testace module");#}
                editor = ace.edit("id_tool_script_editor");
                editor.setTheme("ace/theme/xcode");
                editor.session.setMode("ace/mode/yaml");
                editor.setOptions({
                    enableBasicAutocompletion: true,
                    enableSnippets: true,
                    enableLiveAutocompletion: true
                });
                require(["ace/requirejs/text!src/ace"], function (e) {
                    editor.setValue($('#id_tool_script').val());
                })
            }
        );
        require(['editor'])

        $('#id_tool_run_type').change(function (e) {
            if ($('#id_tool_run_type').val() == "0") {
                editor.session.setMode("ace/mode/yaml");
            }
            if ($('#id_tool_run_type').val() == "1") {
                editor.session.setMode("ace/mode/sh");
            }
            if ($('#id_tool_run_type').val() == "2") {
                editor.session.setMode("ace/mode/powershell");
            }
            if ($('#id_tool_run_type').val() == "3") {
                editor.session.setMode("ace/mode/python");
            }
            if ($('#id_tool_run_type').val() == "4") {
                editor.session.setMode("ace/mode/plain_text");
            }
            if ($('#id_tool_run_type').val() == "5") {
                editor.session.setMode("ace/mode/plain_text");
            }
        })
    </script>

{% endblock %}

templates/frontend/tools_manager/tools_script_list.html
{% extends 'frontend/common/basic_list.html' %}

{% block list_title %}
    工具
{% endblock %}

{% block list_filter %}
    <div class="col-sm-2">
        <select class="form-control m-b" name="tools_type">
            <option value="" {% ifequal '' kwargs.tools_type %}
                    selected="selected"
            {% endifequal %}
            >工具类型
            </option>
            {% for o in plugin_result.tools_types %}
                <option value="{{ o.id }}" {% ifequal o.id kwargs.tools_type|str_to_int %}
                        selected="selected"
                {% endifequal %}

                >{{ o.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-sm-2">
        <div class="input-group">
            <input type="text" name="name__contains" placeholder="工具名称"
                   value="{{ kwargs.name__contains }}"
                   class="input-sm form-control">
        </div>
    </div>
    <div class="col-sm-2">
        <select class="form-control m-b" name="tool_run_type">
            <option value="" {% ifequal '' kwargs.tool_run_type %}
                    selected="selected"
            {% endifequal %}
            >脚本类型
            </option>
            <option value="0" {% ifequal kwargs.tool_run_type|str_to_int  0 %}
                    selected="selected"
            {% endifequal %}
            >SaltState
            </option>
            <option value="1" {% ifequal kwargs.tool_run_type|str_to_int 1 %}
                    selected="selected"
            {% endifequal %}
            >Shell
            </option>
            <option value="2" {% ifequal kwargs.tool_run_type|str_to_int 2 %}
                    selected="selected"
            {% endifequal %}
            >PowerShell
            </option>
            <option value="3" {% ifequal kwargs.tool_run_type|str_to_int 3 %}
                    selected="selected"
            {% endifequal %}
            >Python
            </option>
            <option value="4" {% ifequal kwargs.tool_run_type|str_to_int 4 %}
                    selected="selected"
            {% endifequal %}
            >Salt命令
            </option>
            <option value="5" {% ifequal kwargs.tool_run_type|str_to_int 5 %}
                    selected="selected"
            {% endifequal %}
            >Windows批处理
            </option>
        </select>
    </div>
    <div class="col-sm-4">
        <div class="input-group">
            &nbsp;
            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> 搜索</button>
            &nbsp;
            <a href="tools_script_add/"
               class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 新增</a>
            &nbsp;
            <a href="javascript:void(0)"
               onclick="deleteBatch()"
               class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> 批量删除</a>
        </div>
    </div>
{% endblock %}

{% block list_content %}
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable">
        <thead>
        <tr>
            <th style="width: 2%;"><input id="checkall" type="checkbox" class="i-checks"></th>
            <th style="width: 10%;">工具类型</th>
            <th style="width: 10%;">名称</th>
            <th style="width: 7%;">脚本类型</th>
            <th style="width: 20%;">工具说明</th>
            <th style="width: 10%;">创建时间</th>
            <th style="width: 10%;">更新时间</th>
            <th style="width:25%;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for o in result_list %}
            <tr>
                <td>
                    <input type="checkbox" class="i-checks icheck" id="{{ o.id }}" name="input[]">
                </td>
                <td>{{ o.tools_type }}</td>
                <td>{{ o.name }}</td>
                <td>{{ o.tool_run_type|tools_type_filter }}</td>
                <td>{{ o.comment }}</td>
                <td>{{ o.create_time }}</td>
                <td>{{ o.update_time }}</td>
                <td>

                    <a href="{{ o.id }}/tools_script_edit/"
                       class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                    <a href="{{ o.id }}/tool_execute/"
                       class="btn  btn-sm btn-primary"><i class="fa fa-play"></i>执行</a>
                    <a href="{{ o.id }}/tool_execute_history/"
                       class="btn  btn-sm btn-success"><i class="fa fa-expand"></i>历史</a>
                    <a href="{{ o.id }}/delete_entity/"
                       class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/frontend/tools_manager/tools_types_list.html
{% extends 'frontend/common/basic_list.html' %}

{% block list_title %}
    工具类型
{% endblock %}

{% block list_filter %}
    <div class="col-sm-4">
        <div class="input-group">
            &nbsp;
            <a href="/frontend/tools_manager/tools_types_list/tools_types_add/"
               class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 新增</a>
            &nbsp;
            <a href="javascript:void(0)"
               onclick="deleteBatch()"
               class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> 批量删除</a>
        </div>
    </div>
{% endblock %}

{% block list_content %}
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable">
        <thead>
        <tr>
            <th style="width: 2%;"><input id="checkall" type="checkbox" class="i-checks"></th>
            <th style="width: 10%;">名称</th>
            <th style="width: 10%;">工具数量</th>
            <th style="width: 15%;">创建时间</th>
            <th style="width: 15%;">更新时间</th>
            <th style="width:10%;">操作</th>
        </tr>
        </thead>
        <tbody>
        {% for o in result_list %}
            <tr>
                <td>
                    <input type="checkbox" class="i-checks icheck" id="{{ o.id }}" name="input[]">
                </td>
                <td>{{ o.name }}</td>
                <td>{{ o.id|tools_count }}</td>
                <td>{{ o.create_time }}</td>
                <td>{{ o.update_time }}</td>
                <td>
                    <a href="/frontend/tools_manager/tools_types_list/{{ o.id }}/tools_types_edit/"
                       class="btn  btn-sm btn-info"><i class="fa fa-edit"></i>编辑</a>
                    <a href="/frontend/tools_manager/tools_types_list/{{ o.id }}/delete_entity/"
                       class="btn  btn-sm btn-danger"><i class="fa fa-trash"></i>删除</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}